### PR TITLE
Prevent crashing if initScript element does not exist

### PR DESCRIPTION
**Pull request by guzzur**
## Context

image

### CODE REVIEW

**Comment by nir0s** [comment]
lol. Funny. You know what I had in my clipboard?


image

**Review by nir0s — COMMENTED** [review]
I'm not quite sure I understand how we can simply ignore the fact that they're unavailable. Will we be able to generate a token like this?

**Comment by guzzur** [comment]
> I'm not quite sure I understand how we can simply ignore the fact that they're unavailable. Will we be able to generate a token like this?

This indicates a real bug I will be solving next. Some of the flows are not going through the init. This is only the symptom I want to get rid of to get to the real problem.

**Comment by nir0s** [comment]
Right, but then why would you want to prevent a crash at all? Actually, it's quite the opposite if I think about it. We should never get to this. WDYT?

**Comment by guzzur** [comment]
> Right, but then why would you want to prevent a crash at all? Actually, it's quite the opposite if I think about it. We should never get to this. WDYT?

This should be then written in a different way. We should ensure the element exists before we get here. It is not bad not having this symptomatic noise right now, until we solve the root cause.

**Pull request merged**
